# Generated by Django 5.0.6 on 2024-07-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiblogApp', '0002_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
